### ISSUE TITLE
Single scrollbar for whole page

### ISSUE THREAD

**Issue by mwisnicki** [waffleio/waffle.io#1817]

**Comment by ashumz** [comment]
Hi @mwisnicki - what would the value of this be for your team? We've found that teams tend to have a varied number of issues per column, and scrolling by column has been a highly requested feature in the past. Would you prefer a single scroll bar over column scroll or in addition to?

Thanks :)

Ashley

**Comment by mwisnicki** [comment]
Just single scrollbar for whole board like in other similar software. I find that scrollbars make the board too complex and obscure the view. And not just scrollbars. IMHO task board should have as little chrome (UI elements) as possible, so I also dislike your dark title bar and buttons.

This user style is a draft of what I would prefer to see:

```css
  .board {
    overflow: auto;
  }
  
  .column-ct {
    padding-bottom: 20px;
  }
  
  .column {
    overflow: visible !important;
  }
  
  .column-body {
    overflow-y: visible !important;
    height: auto;
  }
  
  .card {
    box-shadow: 1px 1px 1px rgba(0, 0, 0, 0.2) !important;
    margin-bottom: 8px !important;
    background-color: #FFFFD4 !important; /* TODO tint depending on type/tag */
  }
  
  .card-header {
    display: none;
  }
  
  .card-body {
    background-color: transparent !important;
  }
  
  .card .title {
    background: transparent;
    min-height: 42px !important;
    font-family: sans-serif !important;
    font-size: 14px !important;
  }
```
