### ISSUE TITLE
ENH,UBY: lower [ul.task-list ul,] padding-left to 18px

### ISSUE THREAD

**Issue by westurner** [waffleio/waffle.io#2544]
This seems to make task lists less unnecessarily indented:

```css
ul.task-list ul { 
    padding-left: 18px; 
}
```
